CREATE TABLE Customer(
Customer_ID	INTEGER NOT NULL,
Last_Name VARCHAR(20) NOT NULL,
First_Name VARCHAR(20) NOT NULL,
Phone VARCHAR(20)
CONSTRAINT Customer_PK PRIMARY KEY (Customer_ID)
)
;
CREATE TABLE Card(
Card_ID	INTEGER NOT NULL,
Owner_ID INTEGER NOT NULL,
Discount FLOAT NOT NULL,
CONSTRAINT Card_PK PRIMARY KEY (Card_ID)
)
;
CREATE TABLE Order(
Order_ID INTEGER NOT NULL,
Card_ID INTEGER
Cost FLOAT NOT NULL,
Points INTEGER
Marker_ID INTEGER NOT NULL,
CONSTRAINT Order_PK PRIMARY KEY (Order_ID)
)
;
CREATE TABLE Base(
ID	INTEGER NOT NULL,
Order_ID INTEGER NOT NULL,
Product_ID INTEGER NOT NULL,
CONSTRAINT Base_PK PRIMARY KEY (ID)
)
;
CREATE TABLE Product(
Product_ID	INTEGER NOT NULL,
Product_Type_ID INTEGER NOT NULL,
Cost FLOAT NOT NULL,
CONSTRAINT Product_PK PRIMARY KEY (Product_ID)
)
;
CREATE TABLE Product_Type(
Product_Type_ID	INTEGER NOT NULL,
Name VARCHAR(20) NOT NULL,
Discount_influence FLOAT NOT NULL,
CONSTRAINT Product_Type_PK PRIMARY KEY (Product_Type_ID)
)
;
